apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: devops-tools
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8080'
spec:
  selector:
    app: jenkins-server
  ports:
    - protocol: TCP
      port: 80   # The port on which the service will be exposed
      targetPort: 8080  # The port on which your application is running inside the pods
  type: LoadBalancer
